[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/mattn/go-tty"

[[constraint]]
  name = "github.com/mingrammer/cfmt"
  version = "1.1.0"

[[constraint]]
  name = "github.com/jessevdk/go-flags"
  version = "1.4.0"
